name: Build Godot Engine for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'  # Use 'temurin' for the JDK distribution

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip clang build-essential scons git wget unzip

      - name: Install Android SDK
        run: |
          # Download Android SDK command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O android-sdk-tools.zip
          unzip android-sdk-tools.zip -d android-sdk
          rm android-sdk-tools.zip

      - name: Install Android SDK and NDK
        run: |
          # Install Android SDK tools
          export ANDROID_HOME=$(pwd)/android-sdk
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin
          yes | ./android-sdk/cmdline-tools/bin/sdkmanager --licenses
          ./android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
          
          # Install Android NDK (for building Godot)
          ./android-sdk/cmdline-tools/bin/sdkmanager "ndk;21.4.7075529"

      - name: Download Godot Export Templates
        run: |
          mkdir -p godot_export
          cd godot_export
          wget https://downloads.tuxfamily.org/godotengine/3.6/export_templates/godot-3.6-stable-export-templates.tpz
          tar -xvzf godot-3.6-stable-export-templates.tpz
          cd ..

      - name: Build Godot Engine for Android
        run: |
          cd android/godot_source_code
          scons platform=android target=release tools=yes

      - name: Upload Build Artifacts (APK)
        uses: actions/upload-artifact@v3
        with:
          name: godot-android-apk
          path: android/godot_source_code/bin/godot.apk
